# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df8fe8c929946e0cdc6b03e7708ad6d4e60a1df2046b843e6b126cefffadc8d2bb6e383ea496526139af096f148a09313967c9c3b2341a5cc3e36a77c73b5732

test:
  secret_key_base: 042766525439b6510433d6c145155e05d7c61fcde7f0bb4007826b8223d0a006e3fa83a7693c213b4f9856204c5b4c046827415976143916a69d5d77e53279f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
